import type { Request, Response } from "express";
import { Prisma } from "@prisma/client";
import { prisma } from "../prisma/client";
import { ApiError } from "../utils/apiError";
const number = () => `${Date.now()}${Math.floor(Math.random() * 1000)}`;
const pagination = (q: { page?: number; pageSize?: number }) => ({ skip: ((q.page ?? 1) - 1) * (q.pageSize ?? 10), take: q.pageSize ?? 10 });
const productLines = async (lines: Array<{ productId: string }>) => { const ids = [...new Set(lines.map((line) => line.productId))]; const products = await prisma.product.findMany({ where: { id: { in: ids }, status: "PUBLISHED", b2bEligible: true }, select: { id: true } }); if (products.length !== ids.length) throw new ApiError(400, "One or more products are unavailable for B2B requests", "PRODUCT_UNAVAILABLE"); };
export const b2bController = {
  createQuote: async (req: Request, res: Response) => { await productLines(req.body.lines); const customer = req.customer; if (customer && customer.email !== req.body.email.toLowerCase()) throw new ApiError(403, "Authenticated customers must use their account email", "QUOTE_EMAIL_MISMATCH"); const quote = await prisma.quote.create({ data: { quoteNumber: `RFQ-${number()}`, customerId: customer?.customerId, contactName: req.body.contactName, company: req.body.company, email: req.body.email.toLowerCase(), phone: req.body.phone, deliveryAddress: req.body.deliveryAddress, notes: req.body.notes, lines: { create: req.body.lines } }, include: { lines: { include: { product: { select: { id: true, name: true, slug: true } } } } } }); res.status(201).json({ data: quote }); },
  listQuotes: async (req: Request, res: Response) => { const q = res.locals.validatedQuery; const [data, total] = await Promise.all([prisma.quote.findMany({ where: { customerId: req.customer!.customerId }, ...pagination(q), include: { lines: { include: { product: { select: { name: true, slug: true } } } } }, orderBy: { createdAt: "desc" } }), prisma.quote.count({ where: { customerId: req.customer!.customerId } })]); res.json({ data, meta: { page: q.page, pageSize: q.pageSize, total } }); },
  getQuote: async (req: Request, res: Response) => { const quote = await prisma.quote.findFirst({ where: { id: req.params.id as string, customerId: req.customer!.customerId }, include: { lines: { include: { product: { select: { name: true, slug: true } } } } } }); if (!quote) throw new ApiError(404, "Quote not found", "QUOTE_NOT_FOUND"); res.json({ data: quote }); },
  createSample: async (req: Request, res: Response) => { await productLines(req.body.lines); const customer = req.customer; if (customer && customer.email !== req.body.email.toLowerCase()) throw new ApiError(403, "Authenticated customers must use their account email", "SAMPLE_EMAIL_MISMATCH"); const sample = await prisma.sampleRequest.create({ data: { customerId: customer?.customerId, contactName: req.body.contactName, company: req.body.company, email: req.body.email.toLowerCase(), phone: req.body.phone, businessType: req.body.businessType, expectedMonthlyVolume: req.body.expectedMonthlyVolume, intendedUse: req.body.intendedUse, deliveryAddress: req.body.deliveryAddress, lines: { create: req.body.lines.map((line: { productId: string; quantity: number; unit: string }) => ({ productId: line.productId, requestedQuantity: line.quantity, unit: line.unit })) } }, include: { lines: true } }); res.status(201).json({ data: sample }); },
  listSamples: async (req: Request, res: Response) => { const q = res.locals.validatedQuery; const [data, total] = await Promise.all([prisma.sampleRequest.findMany({ where: { customerId: req.customer!.customerId }, ...pagination(q), include: { lines: { include: { product: { select: { name: true, slug: true } } } } }, orderBy: { createdAt: "desc" } }), prisma.sampleRequest.count({ where: { customerId: req.customer!.customerId } })]); res.json({ data, meta: { page: q.page, pageSize: q.pageSize, total } }); },
  getSample: async (req: Request, res: Response) => { const sample = await prisma.sampleRequest.findFirst({ where: { id: req.params.id as string, customerId: req.customer!.customerId }, include: { lines: { include: { product: { select: { name: true, slug: true } } } } } }); if (!sample) throw new ApiError(404, "Sample request not found", "SAMPLE_NOT_FOUND"); res.json({ data: sample }); },
  listOrders: async (req: Request, res: Response) => { const q = res.locals.validatedQuery; const [data, total] = await Promise.all([prisma.order.findMany({ where: { customerId: req.customer!.customerId }, ...pagination(q), include: { lines: true }, orderBy: { createdAt: "desc" } }), prisma.order.count({ where: { customerId: req.customer!.customerId } })]); res.json({ data, meta: { page: q.page, pageSize: q.pageSize, total } }); },
  getOrder: async (req: Request, res: Response) => { const order = await prisma.order.findFirst({ where: { id: req.params.id as string, customerId: req.customer!.customerId }, include: { lines: true } }); if (!order) throw new ApiError(404, "Order not found", "ORDER_NOT_FOUND"); res.json({ data: order }); },
  createOrder: async (req: Request, res: Response) => { if (!req.body.quoteId) throw new ApiError(422, "Orders can only be created from an accepted quote", "QUOTE_REQUIRED"); const quote = await prisma.quote.findFirst({ where: { id: req.body.quoteId, customerId: req.customer!.customerId, status: "ACCEPTED" }, include: { lines: { include: { product: true } } } }); if (!quote || quote.lines.some((line) => !line.quotedPrice)) throw new ApiError(422, "An accepted quote with quoted prices is required", "QUOTE_NOT_ORDERABLE"); const order = await prisma.$transaction(async (tx) => { const lines = quote.lines.map((line) => ({ productId: line.productId, productName: line.product.name, quantity: line.quantity, unit: line.unit, packSize: line.packSize, unitPrice: line.quotedPrice!, lineTotal: line.quotedPrice!.mul(line.quantity) })); const subtotal = lines.reduce((sum, line) => sum.add(line.lineTotal), new Prisma.Decimal(0)); return tx.order.create({ data: { orderNumber: `ORD-${number()}`, customerId: req.customer!.customerId, subtotal, total: subtotal, billingAddress: req.body.billingAddress, shippingAddress: req.body.shippingAddress, notes: req.body.notes, lines: { create: lines } }, include: { lines: true } }); }); res.status(201).json({ data: order }); },
  reorder: async (req: Request, res: Response) => { const order = await prisma.order.findFirst({ where: { id: req.params.id as string, customerId: req.customer!.customerId }, include: { lines: true } }); if (!order) throw new ApiError(404, "Order not found", "ORDER_NOT_FOUND"); const quote = await prisma.quote.create({ data: { quoteNumber: `RFQ-${number()}`, customerId: req.customer!.customerId, contactName: req.customer!.email, email: req.customer!.email, notes: `Reorder request based on ${order.orderNumber}`, lines: { create: order.lines.map(({ productId, quantity, unit, packSize }) => ({ productId, quantity, unit, packSize })) } }, include: { lines: true } }); res.status(201).json({ data: quote }); },
  prices: async (req: Request, res: Response) => { const product = await prisma.product.findFirst({ where: { id: req.params.id as string, status: "PUBLISHED" } }); if (!product) throw new ApiError(404, "Product not found", "PRODUCT_NOT_FOUND"); const tier = req.customer?.status === "ACTIVE" ? "B2B" : "RETAIL"; const data = await prisma.productPrice.findMany({ where: { productId: product.id, tier, validFrom: { lte: new Date() }, OR: [{ validUntil: null }, { validUntil: { gte: new Date() } }] }, orderBy: { minQuantity: "asc" } }); res.json({ data: { product: { id: product.id, name: product.name }, tier, prices: data } }); },
  distributor: async (req: Request, res: Response) => res.status(201).json({ data: await prisma.distributorApplication.create({ data: req.body }) }),
  exportInquiry: async (req: Request, res: Response) => res.status(201).json({ data: await prisma.exportInquiry.create({ data: req.body }) }),
};
